### ISSUE TITLE
Make more useful

### ISSUE THREAD

**Issue by Roxiun** [TheSavageTeddy/textFormatter#2]
Please make the tool more useful to majority to people. Right now it is spefically tailored to a very specific need and is not useful for people

**Comment by TheSavageTeddy** [comment]
Can you expand more? As in ways to make it better?

**Comment by TheSavageTeddy** [comment]
Also I didn't intend this specially for use for other people I only put it here just for people who want to see it, otherwise I made this for my own use

**Comment by Roxiun** [comment]
ok then
